# Contributed by team cufe
name: cufe_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - algorithm: cufe
            dataset: random-xs
            track: streaming
      fail-fast: false

    steps:
    - uses: actions/checkout@v2 # Pull the repository

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements_py3.10.txt
        python install.py --neurips23track $TRACK --algorithm $ALGO
      env:
        ALGO: ${{ matrix.algorithm }}
        TRACK: ${{ matrix.track }}

    - name: Run the benchmark
      run: |
        python create_dataset.py --dataset $DATASET
        python run.py --neurips23track $TRACK --algorithm $ALGO --dataset $DATASET --runbook_path neurips23/streaming/simple_runbook.yaml
        sudo chmod -R 777 results/
        if [ $TRACK != streaming ]
        then
          python plot.py --dataset $DATASET --neurips23track $TRACK --output plot.png
        fi
        python data_export.py --output test.csv

      env:
        ALGO: ${{ matrix.algorithm}}
        DATASET: ${{ matrix.dataset }}
        TRACK: ${{ matrix.track}}
